packages:
  - packages/**
  - '!**/dist/**'
  - docs

catalog:
  '@antfu/eslint-config': ^6.7.3
  '@antfu/ni': ^28.1.0
  '@cspell/dict-ru_ru': ^2.3.2
  '@iconify-json/carbon': ^1.2.16
  '@iconify-json/fluent-emoji': ^1.2.7
  '@iconify-json/icon-park-outline': ^1.2.4
  '@iconify-json/octicon': ^1.2.19
  '@iconify-json/svg-spinners': ^1.2.4
  '@nolebase/cspell-dict': ^1.3.1
  '@resvg/resvg-wasm': ^2.6.2
  '@rive-app/canvas': ^2.33.3
  '@rollup/plugin-yaml': ^4.1.2
  '@shikijs/vitepress-twoslash': ^3.21.0
  '@types/d3': ^7.4.3
  '@types/d3-force': ^3.0.10
  '@types/debug': ^4.1.12
  '@types/fs-extra': ^11.0.4
  '@types/hast': ^3.0.4
  '@types/markdown-it': ^14.1.2
  '@types/markdown-it-attrs': ^4.1.3
  '@types/markdown-it-footnote': ^3.0.4
  '@types/node': ^24.10.7
  '@types/uuid': ^11.0.0
  '@unlazy/vue': ^1.0.0
  '@unocss/cli': ^66.5.12
  '@unocss/eslint-config': ^66.5.12
  '@unocss/eslint-plugin': ^66.5.12
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-v8': ^4.0.16
  '@vitest/ui': ^4.0.16
  '@vueuse/core': ^14.1.0
  '@vueuse/motion': ^3.0.3
  asciinema-player: ^3.14.0
  builtin-modules: ^5.0.0
  bumpp: ^10.3.2
  canvaskit-wasm: ^0.40.0
  changelogithub: ^14.0.0
  colorette: ^2.0.20
  concurrently: ^9.2.1
  d3: ^7.9.0
  d3-force: ^3.0.0
  date-fns: ^4.1.0
  debug: ^4.4.3
  defu: ^6.1.4
  emoji-regex: ^10.6.0
  es-toolkit: ^1.43.0
  eslint: ^9.39.2
  execa: ^9.6.1
  fs-extra: ^11.3.3
  globby: ^16.1.0
  gray-matter: ^4.0.3
  hast-util-select: ^6.0.4
  hast-util-to-text: ^4.0.2
  less: ^4.5.1
  lint-staged: ^16.2.7
  markdown-it: ^14.1.0
  markdown-it-attrs: ^4.3.1
  markdown-it-footnote: ^4.0.0
  motion: ^12.25.0
  ora: ^9.0.0
  rehype: ^13.0.2
  rehype-meta: ^4.0.1
  rehype-parse: ^9.0.1
  rehype-stringify: ^10.0.1
  retext-stringify: ^4.0.0
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  taze: ^19.9.2
  thumbhash: ^0.1.1
  tinyglobby: ^0.2.15
  typescript: ^5.9.3
  unbuild: ^3.6.1
  uncrypto: ^0.1.3
  unified: ^11.0.5
  unist-util-remove: ^4.0.0
  unist-util-remove-position: ^5.0.0
  unist-util-visit: ^5.0.0
  unlazy: ^1.0.0
  unocss: ^66.5.12
  unplugin-vue-macros: ^2.14.5
  unplugin-yaml: ^3.0.7
  uuid: ^13.0.0
  vite: ^7.3.1
  vite-plugin-inspect: ^11.3.3
  vite-plugin-vue-devtools: ^8.0.5
  vitepress: 2.0.0-alpha.15
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-tsc: ^3.2.2

catalogs:
  vitepress-all:
    vitepress: "^2.0.0-alpha.15"
  vue-3:
    vue: ">= 3.5.26"

catalogMode: strict

neverBuiltDependencies: []
